export const HASH_LENGTH = 32;
export const PIECE_SIZE = 4096;
export const BLOCKS_PER_PIECE = PIECE_SIZE / HASH_LENGTH;
export const ROUNDS = 3;
export const COINBASE_REWARD = 1;
export const DIFFICULTY = 64;
export const VERSION = 1;
export const CHUNK_LENGTH = 8;
export const ERASURE_CODING_SHARDS_LIMIT = 254;
